DevFestEvent/Controllers/MySessionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin;
using Microsoft.Owin.Security.Cookies;
using Owin;
using Microsoft.AspNet.Identity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using DevFestEvent.Models;
using System.Text;
using Google.GData.Client;
using Google.GData.Extensions;
using Google.GData.Spreadsheets;
using DevFestEvent.ViewModels;


namespace DevFestEvent.Controllers
{
    public class MySessionsController : Controller
    {
        //
        // GET: /MySessions/
        public ActionResult Index()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            var s  = db.AppUsers.Find(User.Identity.GetUserId());
            if (s == null)
                return RedirectToAction("Index", "Home");

            db.Entry(s).Collection(c => c.Sessions).Load();
            return View(s);
        }
	}
}

DevFestEvent/Controllers/SpreadsheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;
using Google.GData.Client;
using Google.GData.Extensions;
using Google.GData.Spreadsheets;

using DevFestEvent.Models;
using System.Configuration;

namespace DevFestEvent.Controllers
{
    public class SpreadsheetController : Controller
    {
        //
        // GET: /Spreadsheet/
        public ActionResult Index()
        {
            SpreadsheetsService service;

            service = new SpreadsheetsService("Spreadsheet-GData-Sample-App");
            service.setUserCredentials(
                ConfigurationManager.AppSettings["GoogleUser"],
                 ConfigurationManager.AppSettings["GoogleUserPassword"]);

            SpreadsheetQuery query = new SpreadsheetQuery();
            var feed = service.Query(query);

            return View(feed);
        }

        public ActionResult AllCells()
        {
            SpreadsheetsService service;

            service = new SpreadsheetsService("DevFestEvent");
            service.setUserCredentials(
                ConfigurationManager.AppSettings["GoogleUser"],
                 ConfigurationManager.AppSettings["GoogleUserPassword"]);
            SpreadsheetQuery q = new SpreadsheetQuery(App.SheetFeedData);
            var feed = service.Query(q);
            AtomLink l = feed.Entries.First().Links.FindService(GDataSpreadsheetsNameTable.WorksheetRel, null);
            WorksheetQuery query = new WorksheetQuery(l.HRef.ToString());
            WorksheetFeed f = service.Query(query);

            foreach (var item in f.Entries)
            {
                AtomLink cellFeedLink = item.Links.FindService(GDataSpreadsheetsNameTable.CellRel, null);
                var cellfeedlink = cellFeedLink.HRef.ToString();

                CellQuery cquery = new CellQuery(cellfeedlink);
                CellFeed cfeed = service.Query(cquery);

                Console.WriteLine("Cells in this worksheet:");
                uint rownum = 2;

                foreach (CellEntry curCell in cfeed.Entries)
                {
                    rownum = curCell.Cell.Row;
                }
            }
            return View(f);


        }

        public ContentResult CSS()
        {
            SpreadsheetsService service;

            service = new SpreadsheetsService("DevFestEvent");
            service.setUserCredentials(
                ConfigurationManager.AppSettings["GoogleUser"],
                 ConfigurationManager.AppSettings["GoogleUserPassword"]);
            var cellfeedlink = App.SheetFeedCSS;
            CellQuery cquery = new CellQuery(cellfeedlink);
            CellFeed cfeed = service.Query(cquery);
            string ans = "";

            foreach (CellEntry curCell in cfeed.Entries)
            {
                ans += curCell.Cell.Value;
            }
            return Content(ans, "text/css");

        }


        public ActionResult Schedule()
        {
            SpreadsheetsService service;

            service = new SpreadsheetsService("DevFestEvent");
            service.setUserCredentials(
                ConfigurationManager.AppSettings["GoogleUser"],
                 ConfigurationManager.AppSettings["GoogleUserPassword"]);
            var cellfeedlink = App.SheetFeedData;

            CellQuery cquery = new CellQuery(cellfeedlink);
            CellFeed cfeed = service.Query(cquery);

            Console.WriteLine("Cells in this worksheet:");
            uint rownum = 2;
            List<Session> sessions = new List<Session>();
            Session workingSession = new Session();

            foreach (CellEntry curCell in cfeed.Entries)
            {
                if (curCell.Cell.Row > 1)
                {
                    if (curCell.Cell.Row != rownum)
                    {
                        sessions.Add(workingSession);
                        rownum = curCell.Cell.Row;
                        workingSession = new Session();
                    }
                    switch (curCell.Cell.Column)
                    {
                        case 1:
                            workingSession.IID = int.Parse(curCell.Cell.Value);
                            break;
                        case 2:
                            workingSession.Title = curCell.Cell.Value;
                            break;
                        case 3:
                            workingSession.SpeakerDescription = curCell.Cell.Value;
                            break;
                        case 4:
                            workingSession.Description = curCell.Cell.Value;
                            break;
                        case 5:
                            workingSession.Room = curCell.Cell.Value;
                            break;
                        case 6:
                            workingSession.StartHour = int.Parse(curCell.Cell.Value);
                            break;
                        case 7:
                            workingSession.StartAMPM = curCell.Cell.Value;
                            break;
                        case 8:
                            workingSession.LengthMin = int.Parse(curCell.Cell.Value);
                            break;
                        case 9:
                            workingSession.CSSClass = curCell.Cell.Value;
                            break;
                    }
                }
            }
            sessions.Add(workingSession);
            return View(sessions);
        }

        public bool Update(Session model)
        {
            SpreadsheetsService service;

            service = new SpreadsheetsService("DevFestEvent");
            service.setUserCredentials(
                ConfigurationManager.AppSettings["GoogleUser"],
                 ConfigurationManager.AppSettings["GoogleUserPassword"]);
            SpreadsheetQuery q = new SpreadsheetQuery(App.SheetFeedData);
            // Make a request to the API and get all spreadsheets.
            SpreadsheetFeed feed = service.Query(q);
            if (feed.Entries.Count == 0)
            {
                return false;
            }

            // TODO: Choose a spreadsheet more intelligently based on your
            // app's needs.
            SpreadsheetEntry spreadsheet = (SpreadsheetEntry)feed.Entries[0];
            Console.WriteLine(spreadsheet.Title.Text);

            // Get the first worksheet of the first spreadsheet.
            // TODO: Choose a worksheet more intelligently based on your
            // app's needs.
            WorksheetFeed wsFeed = spreadsheet.Worksheets;
            WorksheetEntry worksheet = (WorksheetEntry)wsFeed.Entries[0];

            // Fetch the cell feed of the worksheet.
            CellQuery cellQ = new CellQuery(worksheet.CellFeedLink);
            CellFeed cfeed = service.Query(cellQ);

            Console.WriteLine("Cells in this worksheet:");
            uint rownum = 2;
            List<Session> sessions = new List<Session>();
            Session workingSession = new Session();

            uint updaterow = 0;
            foreach (CellEntry curCell in cfeed.Entries)
            {
                if (curCell.Cell.Row > 1)
                {
                    if (curCell.Cell.Row != rownum)
                    {
                        sessions.Add(workingSession);
                        rownum = curCell.Cell.Row;
                        workingSession = new Session();
                    }
                    switch (curCell.Cell.Column)
                    {
                        case 1:
                            workingSession.IID = int.Parse(curCell.Cell.Value);
                            if (workingSession.IID == model.IID)
                            {
                                updaterow = curCell.Cell.Row;
                            }
                            break;
                        case 2:
                            if (curCell.Cell.Row == updaterow)
                            {
                                curCell.InputValue = model.Title;
                                curCell.Update();
                            }
                            break;
                        case 3:
                            if (curCell.Cell.Row == updaterow)
                            {
                                curCell.InputValue = model.SpeakerDescription;
                                curCell.Update();
                            }
                            break;
                        case 4:
                            if (curCell.Cell.Row == updaterow)
                            {
                                curCell.InputValue = model.Description;
                                curCell.Update();
                            }
                            break;
                        case 5:
                            if (curCell.Cell.Row == updaterow)
                            {
                            curCell.InputValue = model.Room;
                            curCell.Update();
                            }
                            break;
                        case 6:
                            if (curCell.Cell.Row == updaterow)
                            {
                            curCell.InputValue = model.StartHour.ToString();
                            curCell.Update();
                            }
                            break;
                        case 7:
                            if (curCell.Cell.Row == updaterow)
                            {
                            curCell.InputValue = model.StartAMPM;
                            curCell.Update();
                            }

DevFestEvent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/favicon.png">
    <title>@ViewBag.Title - DevFestMN Sessions</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render(Url.Action("CSS", "Spreadsheet"))
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")" class="navbar-brand"><img src="@Url.Content("~/img/logo.png")" style="height: 30px" /> DevFest Schedule</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("| My Sessions", "Index", "MySessions",null, new { @class = "" })</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Sponsors", "Sponsors", "Home")</li>
                    <!--<li><a href="http://devfest.mn">Full Site</a></li>-->
                </ul>
                <ul>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <div class="row">
            <h4>Google Devfest Twin Cities is proudly sponsored by</h4>
            <div class="sponsors">
                <a href="http://developers.google.com" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://google.com']);">
                    <img class="aligncenter" alt="Logo_Google_2013_Official.svg" src="http://devfest.mn/wp-content/uploads/2014/01/Logo_Google_2013_Official.svg_.png">
                </a>
                <a href="http://leadpages.com" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://leadpages.com']);"><img alt="LeadPages" src="http://devfest.mn/wp-content/uploads/2014/01/leadpages-logo.png"></a>
                <a href="http://code42.com" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://code42.com']);">
                <img alt="Code 42" src="http://devfest.mn/wp-content/uploads/2014/01/code421.png"></a>
                <a href="http://www.stthomas.edu/Business/schulzeschool/default.html" onclick="javascript: _gaq.push(['_trackEvent', 'outbound-article', 'http://www.stthomas.edu/Business/schulzeschool/default.html']);"><img src="http://i.imgur.com/j8Wa6qa.png"></a>
                <a href="http://mentormate.com" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://mentormate.com']);"><img alt="MentorMate" src="http://devfest.mn/wp-content/uploads/2014/01/mentormate-logo-standalone-black-tagline.png"></a>
                <a href="http://www.agosto.com" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://www.agosto.com']);"><img class="alignnone size-medium wp-image-184" alt="Agosto_Logo_Large" src="http://devfest.mn/wp-content/uploads/2014/01/Agosto_Logo_Large-300x148.png" ></a>
                <a href="http://livefront.com" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://livefront.com']);"><img class="alignnone size-full wp-image-196" alt="logo-livefront" src="http://i.imgur.com/dEAmZvz.png"></a>
            </div>
</div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Google DevFest Twin Cities - Site by <a href="https://google.com/+LloydCledwyn">Lloyd Cledwyn</a>
            <br />
            Fully tested for <a href="http://www.google.com/chrome‎">Google Chrome</a>.  Other browsers... not so much.
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/site.js")
    @RenderSection("scripts", required: false)

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-46026381-3', 'devfest.mn');
        ga('send', 'pageview');

    </script>
    <script type="text/javascript">
        (function () {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
    </script>
</body>
</html>

DevFestEvent/Views/Shared/_SessionSchedule.cshtml
@model ICollection<DevFestEvent.Models.Session>
@{
    string hour = "xx";
    string ans = "";
}

@foreach (var s in Model.OrderBy(o => o.StartAMPM).ThenBy(o => o.StartHour).ThenBy(o => o.StartMinute).ThenBy(o => o.Sort))
{
    if (hour != s.FormattedStartTime)
    {
        hour = s.FormattedStartTime;
        ans += @"</div></div><div class='row panel-default'>
                <div class='panel-heading'><strong>" + hour + "</strong></div><div class='panel-body'>";
    }
    ans += @"<div id='session" + s.IID + "'  class='" + s.CSSClass + "' onClick='ShowLessonPopup(" + s.IID + ")'><div class='session'>" + s.Title + "<hr />" +
        @"<div class='roomline'><span class='roomspan'>" + s.Room + "</span></div>" +
        s.SpeakerDescription + "</div></div>";
}
@Html.Raw(ans)

